FROM postgres:latest

RUN apt-get update && apt-get install -y wget unzip

RUN wget -O /tmp/northwind.zip https://github.com/pthom/northwind_psql/archive/master.zip \
    && unzip /tmp/northwind.zip -d /tmp/ \
    && mv /tmp/northwind_psql-master/northwind.sql /docker-entrypoint-initdb.d/

COPY src/database/init-user-db.sh /docker-entrypoint-initdb.d/

RUN chmod a+r /docker-entrypoint-initdb.d/*